# afflux
Izaak Schroeder <izaak.schroeder@gmail.com>
:name: afflux
:description: Functional-reactive flux patterns for React.
:icons: font
:idprefix:
:idseparator: -
:toc:
:toc-placement: preamble

{description}

image:http://img.shields.io/travis/izaakschroeder/{name}/master.svg?style=flat[foo]
image:http://img.shields.io/coveralls/izaakschroeder/{name}/master.svg?style=flat[foo]
image:http://img.shields.io/npm/l/{name}.svg?style=flat[foo]
image:http://img.shields.io/npm/v/{name}.svg?style=flat[bar]
image:http://img.shields.io/npm/dm/{name}.svg?style=flat[baz]

[abstract]
afflux uses [most] to implement a very minimal, fast, functional-reactive style of [flux] patterns for web applications.


## Overview

{name} follows the <<flux>> mantra by providing patterns for actions and stores.

*Actions*:

 * Are dispatchers - Call whenever you need to _do_ something.
 * Are asynchronous - Actions always flow on the next tick.
 * Are streams of promises - You can observe the flow of all actions.
 * Are promises - You can observe for the result of a single action.

Example: "Create a todo with content 'x'".

*Stores*:

 * Are oracles - Call whenever you need to _know_ something.
 * Are synchronous - React only to results of actions.
 * Create properties - Reduce actions to values consumed by views.
 * Domain specific - Encapsulate functionality specific to one domain.

Example: "What are all the known todos?".


TIP: What about the dispatcher? There is none. Everything is a stream. You can emulate all the functionality of a dispatcher with stream combinators.

## Framework Comparison

TODO.

## Usage

Add {name} to your project.

```sh
npm install --save afflux react
```

### Actions

Actions are just functions that create promises. Typically you group your actions together logically in a class that encapsulates the relevant functionality. Actions contain no data about the _state_ of the system.

```javascript
import Promise from 'bluebird';
import { action } from 'afflux';

class MyActions {

    constructor(api) {
        this.api = api;
    }

    @action // <1>
    foo() {
        return this.api.get('/foo');
    }

    @action
    bar() {
        return Promise.reject();
    }
}
```

<1> Use action as an ES7 decorator.

You can create free-standing functions if you wish as well.

```javascript
import { action } from 'afflux';

var example = action((id) => {
	return ajax().then(resp => JSON.parse(resp));
});
```

### Stores

Stores react precisely to the results of actions. Stores _do_ contain the state of the system.

Typically you want:
 * to produce a result that is the combination of multiple actions,
 * to use the result of the promise from the action.

```javascript
class MyStore {
    constructor(actions) {
        this.foo = actions.bar.await();
    }
}
```

### Views

```javascript
import { container, observe } from 'afflux';

@container <1>
class App extends Component {
    render() {
        return <View/>;
    }
}

@observe <2>
class View extends Component {
    render() {
        return <div></div>
    }
}
```

<1> The container HOC
<2> The observe HOC

### Server-Side Rendering

Server-side rendering is possible by waiting until all actions have settled and then outputting the result. Clients can then use this result by having the stores dehydrate their state on the server and rehydrate them on the client.

Every request creates new instances of actions and stores so messages and state from one request don't interfere with those of another.

```javascript
import { render } from 'afflux';
import express from 'express';

let app = express();

app.use((req, res) => {
    let component = <App stores={stores} actions={actions}/>;

    render(component).then(result => {
        res.send(result);
    });
});
```

## Testing

Easy to test using any test framework that supports promises. Such a possible combination is [mocha], [chai] and [chai-as-promised].

### Actions

```javascript
import TodoActions from 'actions/todos.action';
describe('#create', () => {

    let actions;

    beforeEach(() => {
        actions = new TodoActions();
    });

    it('should create a new todo', () => {
        return <1> expect(actions.create).to.eventually.equal({
            foo: 'bar'
        });
    });
});
```

<1> Since actions return promises, we can just test the value of the promise directly.

### Stores

```javascript
import emitter from 'most/sources/emitter';
import never from 'most/sources/never';
import TodoStore from 'stores/todos.store';

describe('todos', () => {
    // Instead of using normal actions, use emitters for everything you
    // want to control and nevers for anything else. This ensures that
    // the merged values stream eventually ends; it will end after all
    // actions have ended.
    let store, actions;

    beforeEach(() => {
        actions = { create: emitter(), update: never };
        store = new TodoStore(actions);
    });

    it('should add created todo', () => {
        create.emit({ id: 5 }).end();
        // Since stores are also promises, we can just test the value of
        // the promise directly.
        return expect(store.todos).to.eventually.contain({ id: 5 });
    });
})
```


[bibliography]
 * [[[flux]]] Flux http://facebook.github.io/flux/
 * [most]: https://github.com/cujojs/most
 * [kefir]: http://pozadi.github.io/kefir
 * [rxjs]: https://github.com/Reactive-Extensions/RxJS
 * [bacon]: https://baconjs.github.io/
 * [fluxxor]: http://fluxxor.com/
 * [fluxible]: https://github.com/yahoo/fluxible
 * [biff]: https://github.com/FormidableLabs/biff
 * [alt]: http://alt.js.org/
 * [blog post]: https://medium.com/@garychambers108/functional-reactive-react-js-b04a8d97a540
